FROM nginx:latest

RUN apt-get update && apt-get install -y snapd

VOLUME /run/snapd.socket:/run/snapd.socket

COPY ./packages/client/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
