FROM nginx:latest

# Обновление пакетов
RUN apt-get update && apt-get upgrade -y

# Установка Midnight Commander
RUN apt-get install -y mc

COPY ./packages/client/nginx.conf /etc/nginx/nginx.conf
COPY ./packages/client/ssl/privkey.pem /etc/ssl/privkey.pem
COPY ./packages/client/ssl/cert.pem /etc/ssl/cert.pem

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]
